### ISSUE TITLE
Does not seem to work with public organization repos.

### ISSUE THREAD

**Issue by ssmereka** [alanshaw/david-www#175]
No repositories are listed when accessing an organization's repositories.

Example:  https://david-dm.org/smartdevicelink

**Comment by mauvm** [comment]
Having the same issue.

**Comment by saibotsivad** [comment]
This issue still exists.

**Comment by saibotsivad** [comment]
Without having tried to run it locally, it looks like the issue is on https://github.com/alanshaw/david-www/blob/master/lib/profile.js#L30

The [Github API](https://developer.github.com/v3/repos/#list-organization-repositories) says "get users repos" is different than "get orgs repos", so the [github module](https://www.npmjs.com/package/github) has a different call for [getTeamRepos](http://mikedeboer.github.io/node-github/#orgs.prototype.getTeamRepos).

**Comment by htanjo** [comment]
I found this could fixed removing `type: "all"` in [profile.js#L30](https://github.com/alanshaw/david-www/blob/v9.4.0/lib/profile.js#L30).

@saibotsivad,
Yes, GitHub has different API for organization, but `repos#getFromUser` can also return org repos. For example: https://api.github.com/users/github/repos
-> This returns "github organization" repos.

@alanshaw,
I'm not sure it works perfectly or not without `type` option because I can't test private repos.
Do you have any concern? I'm planning to send a PR.

**Comment by alanshaw** [comment]
Hey, thanks, please send a PR and I'll double check :)

**Comment by saibotsivad** [comment]
I booted up david-www and checked that patch and it works great. Thanks, @htanjo!

**Comment by htanjo** [comment]
No problem! Glad to solve this. :smile_cat:
