### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by dbkaplun** [alanshaw/david-www#208]
```
$ curl -L david-dm.org # follow redirects
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.4.6 (Ubuntu)</center>
</body>
</html>
```

**Comment by alanshaw** [comment]
Thanks for reporting. The Node Security project renamed the repo where security advisories live and there was no null checking around the code that iterates over the data. This was fixed in https://github.com/alanshaw/david-www/commit/dae6680eddcf9da422800e4cb81a4095bc37be05 and the site is now back up.
