### ISSUE TITLE
Potential security issues reported by Snyk.io

### ISSUE THREAD

**Issue by revelt** [alanshaw/david-www#320]
Snyk reports quite alerting issues with this repo:
https://snyk.io/test/github/alanshaw/david-www
Let's patch up everything that's possible to patch!

**Comment by gravis** [comment]
Nice! That's indeed a sneaky way to do your advertising...

**Comment by revelt** [comment]
Well I have no affiliation with Snyk and it's free for OS, so no money's involved anyway 😃 
But this doesn't change the subject, Snyk gives instructions what's problematic, so let's fix them if possible

**Comment by gravis** [comment]
That's exactly what an advertiser would say :)

**Comment by mk-pmb** [comment]
I think the reason why it looks like ad is that you make it click bait, instead of importing the issues as a todo list. I've tried to do so but failed to extract useful information from the linked site.

> Snyk gives instructions what's problematic,

Its advice for each listed problem is "run our tool to fix it", and the claims of what that tool would do seem to all be about making a modified version of the `couchwatch` module, because its dependencies are insecure and npm currently has no update for `couchwatch`.

> so let's fix them if possible

I don't think any of those fixes are possible in this module and repo, as they are, to my understanding, all about `couchwatch`, so that would have to be fixed first. I hope I'm mistaken, because otherwise the OP seems like outright spam really.

**Comment by revelt** [comment]
ok
