### ISSUE TITLE
Service unstable?

### ISSUE THREAD

**Issue by PeterDaveHello** [alanshaw/david-www#357]
Hi @alanshaw!
I just found that I keep getting error like `Internal Server Error` on https://david-dm.org, and the image/badge is also unavailable. Is there anything I can help? Thanks!

**Comment by JoshSmith** [comment]
@alanshaw anything anyone can do to help on this?

**Comment by pleerock** [comment]
@alanshaw same issues over a month already

**Comment by larshp** [comment]
any news? it is getting really bad

**Comment by PeterDaveHello** [comment]
No offense, if, I mean if, if there is no any updates, maybe we can try to host another one in the meantime.

**Comment by alanshaw** [comment]
I have very limited time to work on david outside of my day job and I'm trying to work on this whenever I can so please be patient.

I believe the most recent downtime was that the david module was upgraded to use npm@4.x whereas the website was still using npm@3.x. I've now updated the website so they're both using the same version. Hopefully that'll help.

The wider issue is that the site is popular, and doing a lot of work on every request. It depends on two external services (github+npm) that sometimes respond slowly to requests. Many requests to david and slow responses from github and/or npm causes a backlog that is difficult for it to clear, causing it to be unable to respond to requests in a reasonable time. The two need to be decoupled so that david can respond quickly to requests, and update dependency information in the background. I'm working to address this.

**Comment by PeterDaveHello** [comment]
@alanshaw thank you very much for your reply, at least we know what the problem is, if you need support or help, maybe could also let us know and we can see what we can help, thanks for your great work on it!

**Comment by JoshSmith** [comment]
@alanshaw I think the consensus feeling here is not that we're frustrated by your lack of time to work on this. Really want to emphasize – even overemphasize if possible – how thankful we are that you do any of this at all.

Rather, I think we'd just love to see what's frustrating you or blocking you right now, raw and out in the open. That way we can help to share the load. It ain't heavy if we help!

**Comment by alanshaw** [comment]
Thanks @JoshSmith those kind of comments make it worth while 😄

**Comment by alanshaw** [comment]
Closing as stability has resumed. Thanks for reporting and all your comments 🥇

**Comment by JoshSmith** [comment]
Awesome thank you for all your hard work on this @alanshaw. :raised_hands:

**Comment by the-j0k3r** [comment]
@alanshaw The issues continue, this is yesterday and today when trying to go anywhere 

![Capture](https://user-images.githubusercontent.com/31389848/131981129-97258af2-7d22-4ce9-a711-850f2c1574d8.PNG)

and this 

![Capture](https://user-images.githubusercontent.com/31389848/131981671-163a58e6-0444-4e8c-b756-60d6642488ba.PNG)

Yesterday it worked here briefly and after half hour it went just as fast.

I was able to visit the basic https://david-dm.org page today, like a minute ago but anything else like badges https://david-dm.org/Style-it-Themes/dd-wrt-inspired-themes?type=dev is at best random mixed bag of results.

![Capture](https://user-images.githubusercontent.com/31389848/131982086-64c3954f-d2cc-4061-b273-18eaecc548e8.PNG)

badges are broken anywho at the time or writing this.
