### ISSUE TITLE
Dependencies still showing out of date for gulp-protractor

### ISSUE THREAD

**Issue by rahulmr** [alanshaw/david-www#367]
Hello,
https://david-dm.org/mllrsohn/gulp-protractor/
The dependencies is shown out of date even though details show everything up to date.
Any clue what is missing from my end.

https://david-dm.org/rahulmr/gulp-protractor/ shows everything green

**Comment by dolanmiu** [comment]
same,

I am getting this with:

https://david-dm.org/dolanmiu/docx

All of it is green, why is the badge red, its so puzzling

**Comment by tocttou** [comment]
Same issue here:

https://david-dm.org/Cloud-CV/cvfy-frontend?type=dev

**Comment by dolezel** [comment]
Same issue:
https://david-dm.org/theoephraim/node-pg-migrate

**Comment by mattstratton** [comment]
Same issue here https://david-dm.org/mattstratton/linter-cookstyle

**Comment by lusentis** [comment]
Same issue here https://david-dm.org/dawson-org/dawson-cli :(

**Comment by dolanmiu** [comment]
I have found a solution.

Use this instead. It is much more reliable and accurate:

https://gemnasium.com/github.com/dolanmiu/docx

**Comment by tocttou** [comment]
This project seems to be not maintained anymore.

**Comment by alanshaw** [comment]
@tocttou this project IS maintained. If you'd like to submit a pull request to fix the issue, it would be appreciated.

**Comment by tocttou** [comment]
Oh cool, I'll take a look.

**Comment by eisbehr-** [comment]
@alanshaw Is the project really maintained?

I mean, two month of a problem with one of the core features, the badges, and it seems like nothing will happen here?! I think the main reason to use `david` are the badges, wich seems not to work correctly anymore, related to the amount of topics about the badges here. And the wrong informations the badges commit will cause users to not use some project, because it seems `insecure`, like your badge is telling them.

There is even no information from you on any topic here, the david page or the blog I've found. So no information about problems, no answer for two month and no updates for three month.

But you call it still _maintained_?

**Comment by alanshaw** [comment]
Thanks for your patients. I believe this bug has been resolved in by https://github.com/alanshaw/david-www/commit/6436f07bec18384d0d83a8e89b7fb40286da5bc8. Please comment if you notice this issue again.

**Comment by rahulmr** [comment]
@alanshaw seems fixed but on devDependencies I see it is orange when it should be red as one of the dev dependency is out of date and red. Check [here][1]

[1]: https://david-dm.org/mllrsohn/gulp-protractor?type=dev

**Comment by alanshaw** [comment]
It shows yellow when < 25% of dependencies are out of date
